// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";

// Explicitly load .env from the monorepo root (two levels up from packages/db)
config({ path: resolve(__dirname, "../../.env") });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DIRECT_URL'),
    // directUrl: env('DIRECT_URL')
  },
});
